### ISSUE TITLE
Usage of java.util.Timer

### ISSUE THREAD

**Issue by agourlay** [johanandren/futiles#15]
Hi,

I have a quick question regarding the implementation of [Timeouts](https://github.com/johanandren/futiles/blob/master/src/main/scala/markatta/futiles/Timeouts.scala)

It uses under the hood a ```java.util.Timer``` to schedule tasks to trigger timeouts.

After some reasearch I have found out that ```java.util.Timer``` could be replaced in most cases by a ```java.util.concurrent.ScheduledExecutorService``` as it performs better.

There is a bit of info in the [javadoc](https://docs.oracle.com/javase/7/docs/api/java/util/Timer.html) and an interesting stackoverflow [questions](http://stackoverflow.com/questions/409932/java-timer-vs-executorservice).

Therefore I performed the change in one my [project](https://github.com/agourlay/cornichon/blob/master/src/main/scala/com/github/agourlay/cornichon/util/Timeouts.scala#L10) that also used this kind of trick to design timeouts to see if it works.

I don't have a proper jmh benchmark to back this up but it does seem to perfom better for my use case.

Anyway, I just wanted to let you know about my research and to get your feedback regarding your choice of going with ```Timer``` in first place.

Thank you for the nice lib!

**Comment by johanandren** [comment]
The way the timer is used here is pretty much what `ScheduledExecutorService` does. The only logic triggered on it is creating/starting of a `Future` on the provided execution context, so it does not block the `Timer` thread, same goes for exceptions in the scheduled code-block, they end up failing the created future, not failing the `Timer` thread, so the problems described does not really apply as far as I can see. The statement about clock drift could be relevant but I couldn't find more details about `Timer` behaviour around that with a quick search though.

**Comment by agourlay** [comment]
Thank you for taking the time to look into it.
You can close this issue if there is nothing else to do here 😃
