### ISSUE TITLE
Make CallingThreadExecutionContext public

### ISSUE THREAD

**Issue by jsw** [johanandren/futiles#20]
Any reason this class shouldn't be made available for public consumption?

**Comment by johanandren** [comment]
It should really only be used if you are super sure about the consequences and when it can be used, so I think I'd prefer to not make it public. If you think you are that sure, I think it's simple enough to duplicate.

**Comment by jsw** [comment]
Fair. I saw a slightly different implementation in another project, so I thought it might be valuable to have a well-known canonical instance.
