### ISSUE TITLE
Set up sbt-ci-release

### ISSUE THREAD

**Issue by mdedetrich** [johanandren/futiles#35]
Not sure what the release story of this project is, but if it publishes to sonatype I can set up [sbt-ci-release](https://github.com/sbt/sbt-ci-release) which has direct integration with sbt-github-actions which would allow you to release new versions of this project just by pushing the appropriate tag to `main`.

I have done this change to numerous lightbend/akka projects so I know it works.

**Comment by johanandren** [comment]
I have previously just published this project manually to sonatype since it's very stable and at most one or two releases a year. Having it automated could be nice, so if you have time and want to do that, sure (but it's not super important)

**Comment by mdedetrich** [comment]
Cool I will go ahead and do the PR, you just need to add the sonatype details to github secrets, i.e.

https://github.com/lightbend/sbt-paradox-project-info/blob/master/build.sbt#L49-L52
